## YAML Template.
---
preset: recommended

enabled:
 - concat_with_spaces

disabled:
 - trailing_comma_in_multiline_array
 - concat_without_spaces
 - blank_line_before_return
 - no_useless_return
 - simplified_null_return   